collector_url: http://dl.bintray.com/snowplow/snowplow-generic/snowplow_scala_stream_collector_0.9.0.zip
collector_binary: snowplow-stream-collector-0.9.0

minBackoff: 3000
maxBackoff: 600000
byte_limit: 4000000
record_limit: 500
time_limit: 60000
shard_count_collector: 1

collectorPort: 8080
collectorCookieExpiration: 365
collectorCookieName: "{{ cookie_name }}"
collectorCookieDomain: "{{ cookie_name }}"
collectorSink: "{{ collector.collectorSink }}" # stdout
collectorSinkKinesisStreamRegion: "{{ region }}"
collectorKinesisStreamGoodName: "{{ collector.collectorKinesisStreamGoodName }}"
collectorKinesisStreamBadName: "{{ collector.collectorKinesisStreamBadName }}"
collectorSinkKinesisMinBackoffMillis: "{{ minBackoff }}"
collectorSinkKinesisMaxBackoffMillis: "{{ maxBackoff }}"
collectorKafkaBrokers: "{{ collector.collectorKafkaBrokers }}"
collectorKafkaTopicGoodName: "{{ collector.collectorKafkaTopicGoodName }}"
collectorKafkaTopicBadName: "{{ collector.collectorKafkaTopicBadName }}"
collectorSinkBufferByteThreshold: "{{ byte_limit }}"
collectorSinkBufferRecordThreshold: "{{ record_limit }}"
collectorSinkBufferTimeThreshold: "{{ time_limit }}"
collectorProduction: no
