---

- name: Create Kinesis streams
  command: >
    aws kinesis create-stream
      --stream-name "{{ item.name }}"
      --shard-count "{{ item.shards }}"
      --region "{{ region }}"
  with_items: "{{ kinesis_streams }}"
  ignore_errors: yes
  tags:
    - provision
    - kinesis
