---

- name: Update the apt index
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - common

- name: Install aptitude
  become: yes
  apt:
    pkg: aptitude
    state: present
  tags:
    - common

- name: Other developer tools
  become: yes
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - default-jre
    - vim
    - htop
    - python-boto3
    - python-boto
    - awscli
    - unzip
    - supervisor
  tags:
    - common

- name: Upgrade all packages
  become: yes
  apt:
    upgrade: safe
  tags:
    - common

#- name: Run supervisord as root
#  become: yes
#  lineinfile:
#    dest: /etc/supervisor/supervisord.conf
#    state: present
#    line: "user=root"
#    insertafter: '^\[supervisord\]'
#    backup: yes
#  tags:
#    - common
#    - supervisor

# https://github.com/ansible/ansible-modules-core/issues/3764
- name: Ensure supervisor launches on boot
  become: yes
  command: systemctl enable supervisor
  tags:
    - common
    - supervisor

- name: Run supervisor
  service:
    name: supervisor
    state: started
  tags:
    - common
    - supervisor
